### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by mez** [RokkinCat/ionic-atom#4]
Started ionic serve -b and then I activated with the command, but I am seeing an empty pane. No preview. What am I doing wrong?

**Comment by claudioferrari** [comment]
Same for me, did you solved it ?

**Comment by michaelboke** [comment]
got also a grayed window

**Comment by danielmadu** [comment]
Me too

**Comment by mez** [comment]
Nope.

**Comment by mez** [comment]
Closing because of no response from codebase owner.
